### ISSUE TITLE
Entries uppercase e lowercase atrapalham o Search

### ISSUE THREAD

**Issue by apabsp** [apabsp/Checkpoint#12]
![image](https://github.com/apabsp/Checkpoint/assets/95260401/44d0ca8f-2f35-4274-88bf-98dab18b6ef5)
![image](https://github.com/apabsp/Checkpoint/assets/95260401/bd9db5e7-4fda-4dc0-a031-ef5a8eef6ae1)

A pesquisa só funciona se todas as letras estiverem corretas. 
Há uma distinção entre uppercase e lowercase na pesquisa.

**Comment by JotaPeans** [comment]
resolvido, foi tracado a pesquisa com __contains por __icontains.
