### ISSUE TITLE
Redirecionamento pós review

### ISSUE THREAD

**Issue by helotanaka** [apabsp/Checkpoint#19]
Após a publicação da review, o site não direciona automaticamente para a página do jogo atualizada com a review. Em vez disso, redireciona para outra página.

Após a review:
![5e9f9dc2-1b28-414c-b57c-e4d386709fe5](https://github.com/apabsp/Checkpoint/assets/130470569/1739de72-674a-4a10-a811-4af9b0de89b3)

O que deveria aparecer:
![ae731e63-ca39-431d-8715-3bd16ca4d00f](https://github.com/apabsp/Checkpoint/assets/130470569/f83a9597-b4e8-4968-a768-ba133fe4bcd3)

**Comment by JotaPeans** [comment]
Esse comportamento é o realmente o esperado
