### ISSUE TITLE
Criação de review vazia

### ISSUE THREAD

**Issue by JotaPeans** [apabsp/Checkpoint#20]
No momento da criação de uma nova review, se não digitado nada e clicar em enviar, a review é criada sem nenhum texto.
![Captura de tela 2024-04-09 193558](https://github.com/apabsp/Checkpoint/assets/63313892/1a9716eb-de9d-44e4-83ef-d285adf037dc)
Review sem nenhum texto.
![Captura de tela 2024-04-09 193549](https://github.com/apabsp/Checkpoint/assets/63313892/1eb0c336-9e00-4301-a41c-25991b97bf1c)

**Comment by JotaPeans** [comment]
Pode ser feita apenas uma validação se o "length" da string no textArea é maior que 0.

**Comment by apabsp** [comment]
Corrigido. Também foi adicionado a checagem da review ser APENAS composta de espaços. Ou seja, ambas reviews: "" e "    " serão negadas.

O fix também funciona para modificações de reviews válidas para reviews vazias.
