### ISSUE TITLE
Avaliação não salva

### ISSUE THREAD

**Issue by ClaraMachadoAj** [apabsp/Checkpoint#22]
![image](https://github.com/apabsp/Checkpoint/assets/133816986/2188302c-c53e-49ec-af39-1ebb0ecdf560)
Ao criar uma avaliação o sistema deveria salva-la automaticamente, entretanto isso não ocorre:

![image](https://github.com/apabsp/Checkpoint/assets/133816986/d19d8623-9243-468d-b1ac-61b4270d5119)

Quando o usuário entra novamente na tela do jogo a avaliação, previamente realizada, não aparece.

**Comment by JotaPeans** [comment]
Corrigido. Quando o usuário já havia feito uma review, o botão de adicionar uma nova review não era renderizado no html, fazendo lançar um erro no JavaScript ao tentar pegar esse botão e adicionar uma ação, sendo que estava retornando nulo( null ), justamente por não ter sido renderizado no html.
