### ISSUE TITLE
Jogos que não possuem avaliação posterior retornam o usuário para a root

### ISSUE THREAD

**Issue by apabsp** [apabsp/Checkpoint#23]
Clicando em uma página cujo rating não foi selecionado antes, sou redirecionado à pagina principal.

Clicando no jogo Left 4 Dead 2, cujo usuário Tony ainda não avaliou:
![image](https://github.com/apabsp/Checkpoint/assets/95260401/1bc4ab30-b5e9-4ac5-a8f4-979a34479322)
![image](https://github.com/apabsp/Checkpoint/assets/95260401/bdb2490f-7f26-4e1f-9060-08262381d7e1)

Clicando no jogo Grand Theft Auto 5, cujo usuário Tony avaliou posteriormente:
![image](https://github.com/apabsp/Checkpoint/assets/95260401/473f48b6-bc18-4406-a2d8-53b004e3be2f)
![image](https://github.com/apabsp/Checkpoint/assets/95260401/381c94ba-8545-4567-9c6c-0f20f5d8fad4)

**Comment by JotaPeans** [comment]
Corrigido. Tinha so que verificar se a avaliação existia antes de tentar passar para o html.
