### ISSUE TITLE
Jogo não existe quando curtido

### ISSUE THREAD

**Issue by apabsp** [apabsp/Checkpoint#9]
![jogoNaoExiste](https://github.com/apabsp/Checkpoint/assets/95260401/a7b9b549-c178-4924-af9f-1a127156b6d1)

Se o usuário curtir um jogo pela primeira vez, essa mensagem aparece. Mesmo com isso, a ação de curtir é realizada normalmente na database.

Essa mensagem não aparece se o usuário já tiver curtido o jogo antes.

**Comment by JotaPeans** [comment]
pronto, resolvido
